CREATE DATABASE CAR_RENTAL;

USE CAR_RENTAL;

CREATE TABLE CAR (
Plate_id VARCHAR(30) PRIMARY KEY,
License_no VARCHAR(30) UNIQUE,
Car_name VARCHAR(30),
Car_type VARCHAR(30),
Year VARCHAR(30),
Daily_rate VARCHAR(30),
Status VARCHAR(30),
Office_location VARCHAR(30)
);

CREATE TABLE CUSTOMER (
Customer_id int NOT NULL AUTO_INCREMENT,
Driving_license_no VARCHAR(30) UNIQUE,
Email VARCHAR(30) UNIQUE,
Password VARCHAR(30),
Fname VARCHAR(30),
Lname VARCHAR(30),
Mobile_no VARCHAR(30),
Plate_id VARCHAR(30),
PRIMARY KEY (Customer_id),
FOREIGN KEY (Plate_id) REFERENCES CAR(Plate_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE RESERVATION (
Reservation_id int UNIQUE AUTO_INCREMENT,
Customer_id int,
Reservation_date DATE,
PickUp_date DATE,
Return_date DATE,
Payment_Date DATE,
Number_days VARCHAR(30),
Cost VARCHAR(30),
Plate_id VARCHAR(30),
PRIMARY KEY (Customer_id, Plate_id),
FOREIGN KEY (Plate_id) REFERENCES CAR(Plate_id) ON UPDATE CASCADE ON DELETE RESTRICT,
FOREIGN KEY (Customer_id) REFERENCES CUSTOMER(Customer_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE `ADMIN` (
Admin_id  VARCHAR(30) PRIMARY KEY,
Admin_name VARCHAR(30),
Email VARCHAR(30) UNIQUE,
Password VARCHAR(30),
Reservation_id int,
FOREIGN KEY (Reservation_id) REFERENCES RESERVATION(Reservation_id) ON UPDATE CASCADE ON DELETE RESTRICT
);